= Environment

NOTE: The Environment book describes the application domain and external context, physical or virtual (or a mix), in which the system will operate (see {Handbook}).

== E.1 Glossary

NOTE: Clear and precise definitions of all the vocabulary specific to the application domain, including technical terms, words from ordinary language used in a special meaning, and acronyms (see {Handbook}).

WARNING: This chapter should not be empty (following the Glossary Principle_, p.27 of the {handbook}).

Example of terms definition.

[[e1-terms]]
=== `E.1.{counter:e1}` Terms

[[Book]]
{Book}:: Copy of a book with a copy number and an availability status.

[[Catalog]]
{Catalog}:: List of library <<Book,books>> and their instance availability.

== E.2 Components

NOTE: List of elements of the environment that may affect or be affected by the system and project. Includes other systems to which the system must be interfaced (see {Handbook}).

{emptysec}

== E.3 Constraints

NOTE: Obligations and limits imposed on the project and system by the environment (see {Handbook}).

WARNING: This chapter should not be empty (following the _Minimum Requirements Outcome Principle_, p.27 of the {handbook}).

== E.4 Assumptions

NOTE: Properties of the environment that may be assumed, with the goal of facilitating the project and simplifying the system (see {Handbook}).

{emptysec}

== E.5 Effects

NOTE: Elements and properties of the environment that the system will affect (see {Handbook}).

{emptysec}

== E.6 Invariants

NOTE: Properties of the environment that the system's operation must preserve (see {Handbook}).

{emptysec}
