= Project

NOTE: The Project book describes all the constraints and expectations not about the system itself, but about how to develop and produce it.

== P.1 Roles and personnel

NOTE: Main responsibilities in the project; required project staff and their needed qualifications (see {Handbook}).

{emptysec}

== P.2 Imposed technical choices

NOTE: Any a priori choices binding the project to specific tools, hardware, languages or other technical parameters (see {Handbook}).

{emptysec}

== P.3 Schedule and milestones

NOTE: List of tasks to be carried out and their scheduling (see {Handbook}).

WARNING: This chapter should not be empty (following the _Minimum Requirements Outcome Principle_, p.27 of the {handbook}).

== P.4 Tasks and deliverables

NOTE: Details of individual tasks listed under P.3 and their expected outcomes (see {Handbook}).

WARNING: This chapter should not be empty (following the _Minimum Requirements Outcome Principle_, p.27 of the {handbook}).

== P.5 Required technology elements

NOTE: External systems, hardware and software, expected to be necessary for building the system (see {Handbook}).

{emptysec}

== P.6 Risk and mitigation analysis

NOTE: Potential obstacles to meeting the schedule of P.4, and measures for adapting the plan if they do arise (see {Handbook}).

{emptysec}

== P.7 Requirements process and report

NOTE: Initially, description of what the requirements process will be; later, report on its steps (see {Handbook}).

{emptysec}
