name: Antora Pages Deploy 

on:
  push:
    branches: 
      - master
env:
  SITE_DIR: 'site/main/1.0'
jobs:
  build_site:
    name: "Build site with Antora"
    runs-on: [ubuntu-latest]
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Install missing npm"
        run: npm i asciidoctor-kroki
      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@master
        with:
         antora_playbook: playbook.yml
      - name: "Upload generated site"
        uses: actions/upload-artifact@v1.0.0
        with:
          name: site
          path: "${{ github.workspace }}/build/${{ env.SITE_DIR }}"